In [4]:
import numpy as np
import cv2

In [5]:
cap=cv2.VideoCapture(0)
face_cascade=cv2.CascadeClassifier("C:/Users/surender/Face Detect/Face Recognition using Haar Cascade Classifier/haarcascade_frontalface_alt.xml")
path='./face_data/'
file_name=input("Enter your name ")
face_data=[]

Enter your name Shrey


In [6]:
while True:
    ret,frame=cap.read()
    
    if(ret==False):
        continue

    #frame=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    faces=face_cascade.detectMultiScale(frame,1.3,5)
    
    if(len(faces)==0):
        continue
        
    faces=sorted(faces, key=lambda f:f[2]*f[3])
    
    for face in faces[-1:]:
        x,y,w,h=face
        cv2.rectangle(frame,(x,y),(x+w,y+h),(255,0,0),3)
        offset=10
        face_section=frame[y-offset:y+offset+h,x-offset:x+offset+w]
        face_section=cv2.resize(face_section,(100,100))
        face_data.append(face_section)
        
        '''eye = eye_cascade.detectMultiScale(frame)
        
        if(len(eyes)==0):
            continue
            
            x2,y2,w2,h2=eye
            cv2.rectangle(frame,(x2,y2),(x2+w2,y2+h2),(0,0,255),3)'''
            
    
    cv2.imshow("frame",frame)
    
    key_press=cv2.waitKey(1) & 0XFF
    if(key_press==ord('q')):
        break

face_data=np.asarray(face_data)
print(face_data)
print(face_data.shape)
    
face_data=face_data.reshape((face_data.shape[0],-1))
print(face_data)
print(face_data.shape)

np.save(path+file_name+'.npy',face_data)
print("Data Saved")
        
cap.release()
cv2.destroyAllWindows()

[[[[ 26  24  14]
   [ 23  23  16]
   [ 23  24  18]
   ...
   [ 45  46  45]
   [ 47  49  48]
   [ 49  51  51]]

  [[ 22  25  12]
   [ 21  24  10]
   [ 21  24  10]
   ...
   [ 45  48  44]
   [ 47  52  50]
   [ 48  54  53]]

  [[ 30  25  11]
   [ 28  24   9]
   [ 27  23   8]
   ...
   [ 61  57  57]
   [ 63  62  62]
   [ 65  65  64]]

  ...

  [[ 48  46  45]
   [ 56  54  53]
   [ 60  57  55]
   ...
   [ 47  44  41]
   [ 45  44  41]
   [ 48  47  44]]

  [[ 51  50  50]
   [ 58  58  58]
   [ 59  60  58]
   ...
   [ 42  46  42]
   [ 42  47  43]
   [ 44  48  44]]

  [[ 55  50  51]
   [ 62  58  58]
   [ 64  60  61]
   ...
   [ 46  47  42]
   [ 48  47  47]
   [ 50  46  51]]]


 [[[ 26  24  14]
   [ 23  23  16]
   [ 23  24  18]
   ...
   [ 45  46  45]
   [ 47  49  48]
   [ 49  51  51]]

  [[ 22  25  12]
   [ 21  24  10]
   [ 21  24  10]
   ...
   [ 45  48  44]
   [ 47  52  50]
   [ 48  54  53]]

  [[ 30  25  11]
   [ 28  24   9]
   [ 27  23   8]
   ...
   [ 61  57  57]
   [ 63  62  62]
   [ 65  65